# Generated by Django 4.2.2 on 2023-08-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_profile', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
