# Generated by Django 4.2.2 on 2023-09-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_new_post', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('data_published', models.DateField(auto_now_add=True)),
                ('image_post', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('new_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_new_post', to='part_post.newpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='the_profile.profile')),
            ],
        ),
    ]
