# Generated by Django 4.2.2 on 2023-10-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_new_post', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('data_published', models.DateField(auto_now_add=True)),
                ('image_post', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
