# Generated by Django 4.2.2 on 2023-10-03 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_profile', '0001_initial'),
        ('part_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_profile.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='new_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_new_post', to='part_post.newpost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='the_profile.profile'),
        ),
    ]
