# Generated by Django 4.2.2 on 2023-08-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_post', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='NewPost',
        ),
    ]
