# Generated by Django 4.2.2 on 2023-09-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_post', '0006_newpost_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
