# Generated by Django 4.2.2 on 2023-10-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_one', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinghotel',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='bookinghotel',
            name='childs',
        ),
        migrations.RemoveField(
            model_name='bookinghotel',
            name='price',
        ),
    ]
