# Generated by Django 4.2.2 on 2023-10-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_one', '0003_remove_bookinghotel_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghotel',
            name='adults',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinghotel',
            name='childs',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinghotel',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
