# Generated by Django 4.2.2 on 2023-10-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_one', '0004_bookinghotel_adults_bookinghotel_childs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeluxeRoomIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='image_room/', verbose_name='Фото')),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Deluxe Room Index',
                'verbose_name_plural': 'Deluxe Rooms Index',
            },
        ),
        migrations.CreateModel(
            name='JuniorSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='image_room/', verbose_name='Фото')),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Junior Suite Room',
                'verbose_name_plural': 'Junior Suite Rooms',
            },
        ),
        migrations.CreateModel(
            name='SuperiorRoomIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='image_room/', verbose_name='Фото')),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Superior Room Index',
                'verbose_name_plural': 'Superior Rooms Index',
            },
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
