# Generated by Django 4.2.2 on 2023-10-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_one', '0005_deluxeroomindex_juniorsuite_superiorroomindex_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeluxeRoomIndex',
        ),
        migrations.DeleteModel(
            name='JuniorSuite',
        ),
        migrations.DeleteModel(
            name='SuperiorRoomIndex',
        ),
    ]
