# Generated by Django 4.2.2 on 2023-10-05 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_one', '0006_delete_deluxeroomindex_delete_juniorsuite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=210)),
                ('photo', models.ImageField(upload_to='restaraunts/')),
                ('average_bill', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoDishRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_photo', models.ImageField(blank=True, upload_to='photo_restaurant/', verbose_name='Фото')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_dish', to='base_one.restaurant', verbose_name='Photo dish')),
            ],
            options={
                'verbose_name': 'dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
