# Generated by Django 4.2.2 on 2023-10-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_one', '0007_restaurant_photodishrestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
