# Generated by Django 4.2.2 on 2023-10-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_one', '0009_roomchat_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='RoomChat',
        ),
    ]
