"""
Django settings for base_site project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k6h*ho&qwszryn04k6y_e^&286&vx-$-q!z9eie2+4@6#52&pe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base_one.apps.PartOneConfig',
    'part_post.apps.PartSecondConfig',
    'part_room.apps.PartRoomConfig',
    'the_profile.apps.TheProfileConfig',
    'paymants.apps.PaymantsConfig',
    'crispy_forms',
    'crispy_bootstrap4',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'base_one.views.AjaxMiddleware',
]

ROOT_URLCONF = 'base_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'part_post.context_processors.my_form',
                'base_one.context_processors.booking_form',
                'part_room.context_processors.room_form',
            ],
        },
    },
]

WSGI_APPLICATION = 'base_site.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'part_room.User'

STRIPE_PUBLISHABLE_KEY = "pk_test_51NuQpzK9uUo7vtk99y6aorEDvSUVs3GZYqzsXrN9CIPyVjmmNHIOnQxVw6aAAcE0p23AKdOhxtKV4mdvk7CC6jvq00nnzbftoo"
STRIPE_SECRET_KEY = "sk_test_51NuQpzK9uUo7vtk9ePb5cBCur9obGtnTq7XXEosZF3Sk7EmR1YM2FPKaCd3XjkzQRtTHFsDiauX6WumWTUlm3gVF00GHwGZBkd"

BACKEND_DOMAIN = 'http://127.0.0.1:8000'
PAYMENT_SUCCESS_URL = 'http://127.0.0.1:8000/success/'
PAYMENT_CANCEL_URL = 'http://127.0.0.1:8000/cancel/'

# from decouple import config
#
# # Stripe
# STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY')
# STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')

STRIPE_WEBHOOK_SECRET = 'whsec_f35c3e7d6488c8c5b90c8277225ca81e33ecbd616e903d4a5a2cdfdaf324cc67'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_POST = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ioann.basic@gmail.com'
EMAIL_HOST_PASSWORD = 'ckjtsltxwatmloia'

DOMAIN_NAME = 'http://127.0.0.1:8000'

CRISPY_TEMPLATE_PACK = 'bootstrap4'
