# Generated by Django 4.2.2 on 2023-09-29 06:11

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, default='/No-Image-Available.jpg', upload_to='', verbose_name='part_room.User')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DeluxeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('add_photo', models.ImageField(upload_to='image_room/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'изображение Deluxe Room',
                'verbose_name_plural': 'Фото Deluxe Room',
            },
        ),
        migrations.CreateModel(
            name='DoubleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('add_photo', models.ImageField(upload_to='image_room/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'изображение Double Room',
                'verbose_name_plural': 'Фото Double Room',
            },
        ),
        migrations.CreateModel(
            name='PhotoDetailRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_photo', models.ImageField(blank=True, upload_to='image_room/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_comment', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('rating_average', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('price', models.IntegerField()),
                ('room_photo', models.ImageField(blank=True, upload_to='')),
                ('arrival_date', models.DateTimeField()),
                ('date_of_departure', models.DateTimeField()),
                ('adults', models.PositiveIntegerField()),
                ('childs', models.PositiveIntegerField()),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SuperiorRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('add_photo', models.ImageField(upload_to='image_room/', verbose_name='Фото')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superior_room', to='part_room.room', verbose_name='Номер в гостинице')),
            ],
            options={
                'verbose_name': 'изображение Superior Room',
                'verbose_name_plural': 'Фото Superior Room',
            },
        ),
    ]
