# Generated by Django 4.2.2 on 2023-08-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
