# Generated by Django 4.2.2 on 2023-08-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0002_room_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/No-Image-Available.jpg', upload_to='', verbose_name='part_room.User'),
        ),
    ]
