# Generated by Django 4.2.2 on 2023-10-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_one', '0002_initial'),
        ('part_room', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='booking',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_room', to='base_one.bookinghotel'),
        ),
    ]
