# Generated by Django 4.2.2 on 2023-09-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='adults',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='arrival_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='childs',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_of_departure',
            field=models.DateTimeField(blank=True),
        ),
    ]
