# Generated by Django 4.2.2 on 2023-08-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperiorRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('add_photo', models.ImageField(upload_to='image_room/', verbose_name='Фото')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_room.room', verbose_name='Номер в гостинице')),
            ],
            options={
                'verbose_name': 'изображение Superior Room',
                'verbose_name_plural': 'Фото Superior Room',
            },
        ),
        migrations.CreateModel(
            name='DoubleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('add_photo', models.ImageField(upload_to='image_room/', verbose_name='Фото')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_room.room', verbose_name='Номер в гостинице')),
            ],
            options={
                'verbose_name': 'изображение Double Room',
                'verbose_name_plural': 'Фото Double Room',
            },
        ),
        migrations.CreateModel(
            name='DeluxeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('add_photo', models.ImageField(upload_to='image_room/', verbose_name='Фото')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_room.room', verbose_name='Номер в гостинице')),
            ],
            options={
                'verbose_name': 'изображение Deluxe Room',
                'verbose_name_plural': 'Фото Deluxe Room',
            },
        ),
    ]
