# Generated by Django 4.2.2 on 2023-09-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0003_alter_room_adults_alter_room_arrival_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='room',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='childs',
        ),
        migrations.RemoveField(
            model_name='room',
            name='date_of_departure',
        ),
        migrations.RemoveField(
            model_name='room',
            name='quantity',
        ),
    ]
