# Generated by Django 4.2.2 on 2023-08-21 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0004_superiorroom_doubleroom_deluxeroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubleroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_double', to='part_room.room', verbose_name='Номер в гостинице'),
        ),
    ]
