# Generated by Django 4.2.2 on 2023-08-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0004_alter_roomimage_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomImage',
            new_name='Images',
        ),
    ]
