# Generated by Django 4.2.2 on 2023-10-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0004_alter_room_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='adults',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='childs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
