# Generated by Django 4.2.2 on 2023-08-21 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0005_alter_doubleroom_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deluxeroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deluxe_room', to='part_room.room', verbose_name='Номер в гостинице'),
        ),
        migrations.AlterField(
            model_name='superiorroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superior_room', to='part_room.room', verbose_name='Номер в гостинице'),
        ),
    ]
