# Generated by Django 4.2.2 on 2023-10-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0005_room_adults_room_childs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='room',
            name='childs',
        ),
    ]
