# Generated by Django 4.2.2 on 2023-10-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0006_remove_room_adults_remove_room_childs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verify_email',
            field=models.BooleanField(default=False, verbose_name='Подтверждение электронной почты'),
        ),
    ]
