# Generated by Django 4.2.2 on 2023-08-21 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0006_alter_deluxeroom_room_alter_superiorroom_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoDetailRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_photo', models.ImageField(blank=True, upload_to='image_room/', verbose_name='Фото')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_room.room', verbose_name='Номер в гостинице')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
