# Generated by Django 4.2.2 on 2023-09-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0008_alter_photodetailroom_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubleroom',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
