# Generated by Django 4.2.2 on 2023-10-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0008_doubleroom_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='deluxeroom',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superiorroom',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
