# Generated by Django 4.2.2 on 2023-09-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0009_doubleroom_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubleroom',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
