# Generated by Django 4.2.2 on 2023-10-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0010_paymenthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
