# Generated by Django 4.2.2 on 2023-09-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_room', '0010_alter_doubleroom_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('add_photo', models.ImageField(upload_to='image_room/', verbose_name='Фото')),
                ('content', models.TextField(default=None)),
            ],
            options={
                'verbose_name': 'изображение Junior Suite ',
                'verbose_name_plural': 'Фото Junior Suite',
            },
        ),
        migrations.CreateModel(
            name='RoomDeluxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('add_photo', models.ImageField(upload_to='image_room/', verbose_name='Фото')),
                ('content', models.TextField(default=None)),
            ],
            options={
                'verbose_name': 'изображение Room Deluxe',
                'verbose_name_plural': 'Фото Room Deluxe',
            },
        ),
        migrations.CreateModel(
            name='RoomDouble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('add_photo', models.ImageField(upload_to='image_room/', verbose_name='Фото')),
                ('content', models.TextField(default=None)),
            ],
            options={
                'verbose_name': 'изображение Room Double',
                'verbose_name_plural': 'Фото Room Double',
            },
        ),
        migrations.CreateModel(
            name='RoomSuperior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('add_photo', models.ImageField(upload_to='image_room/', verbose_name='Фото')),
                ('content', models.TextField(default=None)),
            ],
            options={
                'verbose_name': 'изображение Room Superior',
                'verbose_name_plural': 'Фото Room Superior',
            },
        ),
        migrations.RemoveField(
            model_name='doubleroom',
            name='content',
        ),
    ]
